//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTransportadora.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoFuncionalidade
    {
        public int Id { get; set; }
        public int IdGrupo { get; set; }
        public int IdFuncionalidade { get; set; }
        public bool Inserir { get; set; }
        public bool Ler { get; set; }
        public bool Atualizar { get; set; }
        public bool Excluir { get; set; }
        public bool Executar { get; set; }
    
        public virtual Funcionalidade Funcionalidade { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
