//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTransportadora.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaReferencia
    {
        public int Id { get; set; }
        public int IdPessoa { get; set; }
        public int IdTipoReferencia { get; set; }
        public System.DateTime DataReferencia { get; set; }
        public string Descricao { get; set; }
    
        public virtual TipoReferencia TipoReferencia { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
