//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTransportadora.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetoTransportadoraEntities : DbContext
    {
        public ProjetoTransportadoraEntities()
            : base("name=ProjetoTransportadoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioGrupo> UsuarioGrupo { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Montadora> Montadora { get; set; }
        public virtual DbSet<Canal> Canal { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivil { get; set; }
        public virtual DbSet<Feriado> Feriado { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<RegimeCasamento> RegimeCasamento { get; set; }
        public virtual DbSet<SituacaoVeiculo> SituacaoVeiculo { get; set; }
        public virtual DbSet<TipoResidencia> TipoResidencia { get; set; }
        public virtual DbSet<PessoaEmail> PessoaEmail { get; set; }
        public virtual DbSet<PessoaHistorico> PessoaHistorico { get; set; }
        public virtual DbSet<PessoaReferencia> PessoaReferencia { get; set; }
        public virtual DbSet<PessoaTelefone> PessoaTelefone { get; set; }
        public virtual DbSet<TipoReferencia> TipoReferencia { get; set; }
        public virtual DbSet<TipoTelefone> TipoTelefone { get; set; }
        public virtual DbSet<Funcionalidade> Funcionalidade { get; set; }
        public virtual DbSet<GrupoFuncionalidade> GrupoFuncionalidade { get; set; }
        public virtual DbSet<TipoPessoa> TipoPessoa { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<Veiculo> Veiculo { get; set; }
        public virtual DbSet<SituacaoMulta> SituacaoMulta { get; set; }
        public virtual DbSet<VeiculoHistorico> VeiculoHistorico { get; set; }
        public virtual DbSet<VeiculoMulta> VeiculoMulta { get; set; }
    }
}
