//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTransportadora.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veiculo()
        {
            this.VeiculoHistorico = new HashSet<VeiculoHistorico>();
            this.VeiculoMulta = new HashSet<VeiculoMulta>();
            this.Contrato = new HashSet<Contrato>();
            this.Contrato1 = new HashSet<Contrato>();
        }
    
        public int Id { get; set; }
        public int IdMontadora { get; set; }
        public string Modelo { get; set; }
        public string Placa { get; set; }
        public Nullable<int> AnoFabricacao { get; set; }
        public Nullable<int> AnoModelo { get; set; }
        public string Cor { get; set; }
        public Nullable<int> IdProprietarioAtual { get; set; }
        public Nullable<int> IdProprietarioAnterior { get; set; }
        public string Renavam { get; set; }
        public string Chassi { get; set; }
        public Nullable<System.DateTime> DataAquisicao { get; set; }
        public Nullable<double> ValorAquisicao { get; set; }
        public Nullable<System.DateTime> DataVenda { get; set; }
        public Nullable<double> ValorVenda { get; set; }
        public Nullable<System.DateTime> DataRecuperacao { get; set; }
        public Nullable<System.DateTime> DataValorFIPE { get; set; }
        public Nullable<double> ValorFIPE { get; set; }
        public Nullable<double> ValorTransportadora { get; set; }
        public string Implemento { get; set; }
        public Nullable<double> Comprimento { get; set; }
        public Nullable<double> Altura { get; set; }
        public Nullable<double> Largura { get; set; }
        public string Rastreador { get; set; }
        public Nullable<int> IdSituacaoVeiculo { get; set; }
        public bool Ativo { get; set; }
        public int IdUsuarioCadastro { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<int> IdUsuarioInativacao { get; set; }
        public Nullable<System.DateTime> DataInativacao { get; set; }
    
        public virtual Montadora Montadora { get; set; }
        public virtual Pessoa PessoaProprietarioAnterior { get; set; }
        public virtual Pessoa PessoaProprietarioAtual { get; set; }
        public virtual SituacaoVeiculo SituacaoVeiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeiculoHistorico> VeiculoHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VeiculoMulta> VeiculoMulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato1 { get; set; }
    }
}
