//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTransportadora.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeiculoMulta
    {
        public int Id { get; set; }
        public int IdVeiculo { get; set; }
        public System.DateTime DataMulta { get; set; }
        public string Local { get; set; }
        public int IdCondutor { get; set; }
        public System.DateTime DataVencimentoMulta { get; set; }
        public double ValorMulta { get; set; }
        public int IdSituacaoMulta { get; set; }
        public int IdUsuarioCadastro { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual SituacaoMulta SituacaoMulta { get; set; }
        public virtual Veiculo Veiculo { get; set; }
    }
}
